TST: First test and update for postgis IO (#168)
* TST: First test and update for postgis IO

* BUG: Added trackintel import for `as_triplegs`.

* ENH: Changed connection from sqlalchemy to psycopg2. (experimental)

* CLN: Cleanup of `read_triplegs_postgis` function.

* CLN: Minor spelling mistakes.

* CLN: Correct experimental changes.

* ENH: No CRS have to be set for writing to postgis.

* TST: Added tests for io postgis.

* ENH: Added new model of trips to postgis io.

* TST: Added test for trips postgis io.

* CLN: Removed older not-used tests.

* CLN: Removed developing environment variables.

* BUG: some smaller bugfixes.

* CLN: code format.

* TST: Added test for PostGIS export without any CRS.

* TST: Added docstrings and put `conn_string` and `conn` into one function.

* CLN: Unnecessary scheme creation has been removed.

* TST: Added test for refactored function.

* TST: Added test for checking pfs schema in SQL.

* explicit assignment of env vars

* BLD: Update coverage report
- Switch coverage report from travis to github workflow
- Update coverage report to include postgis coverage

* ENH: Use `gdf.to_postgis` for this module.

* DOC: Replace default of `if_exists`.

Co-authored-by: Christof Leutenegger <christof.leutenegger@hotmail.com>

diff --git a/.github/workflows/CI-tests.yml b/.github/workflows/CI-tests.yml
--- a/.github/workflows/CI-tests.yml
+++ b/.github/workflows/CI-tests.yml
@@ -38,16 +38,16 @@ jobs:
       uses: s-weigand/setup-conda@v1
       with:
         activate-conda: false
-        
+
     - name: Install Env
       shell: bash
       run: conda env create -f ${{ matrix.env }}
-        
+
     - name: Test with pytest
       shell: bash
       run: |
         source activate test
-        pytest --color=yes --cov=./ 
+        pytest -v -r s -n auto --color=yes --cov=trackintel --cov-append --cov-report term-missing --cov-report xml tests/
 
     - name: Test with PostGIS
       shell: bash
@@ -60,4 +60,5 @@ jobs:
         source activate test
         conda install postgis -c conda-forge
         source ci/envs/setup_postgres.sh
-        pytest -v -r s --color=yes --cov=./ | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
+        pytest -v -r s --color=yes --cov=trackintel --cov-append --cov-report term-missing --cov-report xml tests/io/test_postgis_gpd.py | tee /dev/stderr | if grep SKIPPED >/dev/null;then echo "TESTS SKIPPED, FAILING" && exit 1;fi
+    - uses: codecov/codecov-action@v1
